Repository opensearch-project/reporting, pull requests merged in 2022-12, with the labels that each got.

#554 [1.x] Updating dependencies to resolve CVE
  dashboards-reports/package.json
  dashboards-reports/yarn.lock
Labels: backport 1.3

#561 [backport 1.3] Enable windows build
  .github/workflows/dashboards-reports-test-and-build-workflow.yml
  .github/workflows/reports-scheduler-test-and-build-workflow.yml
  dashboards-reports/public/components/main/report_details/__tests__/__snapshots__/report_details.test.tsx.snap
  dashboards-reports/public/components/report_definitions/report_settings/__tests__/__snapshots__/report_settings.test.tsx.snap
  dashboards-reports/test/jest.config.js
Labels: backport 1.3

#568 [1.3] Fix windows CI
  .github/workflows/dashboards-reports-test-and-build-workflow.yml
Labels: backport 1.x

#569 Fix windows and macos CI
  .github/workflows/dashboards-reports-test-and-build-workflow.yml
Labels: backport 2.x

#574 Add ERR_ADDRESS_INVALID in Troubleshooting
  README.md
Labels: backport 1.x

#578 Release notes for 1.3.7
  release-notes/opensearch-dashboards-reports.release-notes-1.3.7.0.md
Labels: backport 1.x

#580 Release notes for 2.4.1
  release-notes/opensearch-dashboards-reports.release-notes-2.4.1.0.md
Labels: backport 2.4

#598 Upgrade dompurify to match upstream
  dashboards-reports/package.json
  dashboards-reports/yarn.lock
Labels: v2.5.0, backport 2.x
