Repository opensearch-project/reporting, pull requests merged in 2022-10, with the labels that each got.

#474 Add release notes for 1.3.6
  reports-scheduler/release-notes/opensearch-dashboards-reports.release-notes-1.3.6.0.md
Labels: backport 1.3

#479 Update jackson to 2.13.4
  reports-scheduler/build.gradle
Labels: backport 1.3

#481 Update 1.3.6 release notes
  release-notes/opensearch-dashboards-reports.release-notes-1.3.6.0.md
Labels: backport 1.3

#506 add groupId = org.opensearch.plugin
  reports-scheduler/build.gradle
Labels: v2.4.0, backport 2.x

#522 Enable Detekt
  reports-scheduler/build.gradle
  reports-scheduler/detekt.yml
  reports-scheduler/src/main/kotlin/org/opensearch/reportsscheduler/index/ReportDefinitionsIndex.kt
  reports-scheduler/src/main/kotlin/org/opensearch/reportsscheduler/index/ReportInstancesIndex.kt
  reports-scheduler/src/main/kotlin/org/opensearch/reportsscheduler/model/ReportDefinition.kt
  reports-scheduler/src/main/kotlin/org/opensearch/reportsscheduler/security/SecurityAccess.kt
  reports-scheduler/src/main/kotlin/org/opensearch/reportsscheduler/settings/PluginSettings.kt
  reports-scheduler/src/test/kotlin/org/opensearch/integTest/ReportSchedularPluginTests.kt
Labels: backport 2.x

#524 Bump loader-utils to 2.0.3 to fix CVE-2022-37601
  dashboards-reports/package.json
  dashboards-reports/yarn.lock
Labels: backport 2.x
