Repository opensearch-project/reporting, pull requests merged in 2023-10, with the labels that each got.

#899 Release Notes 2.11
  release-notes/opensearch-reporting.release-notes-2.11.0.0.md
Labels: backport 2.x, backport main

#912 Upgrade JSON to 20231013 to fix CVE-2023-5072
  build.gradle
Labels: backport 2.x, backport 2.11

#924 Onboard jenkins prod docker images to github actions
  .github/workflows/dco.yml
  .github/workflows/reports-scheduler-release-workflow.yml
  .github/workflows/reports-scheduler-test-and-build-workflow.yml
Labels: enhancement, backport 2.x

#925 [Backport 2.x] Onboard jenkins prod docker images to github actions
  .github/workflows/dco.yml
  .github/workflows/reports-scheduler-release-workflow.yml
  .github/workflows/reports-scheduler-test-and-build-workflow.yml
Labels: enhancement
