Repository opensearch-project/reporting, pull requests merged in 2023-02, with the labels that each got.

#650 Add jackson-databind and jackson-annotations
  build.gradle
Labels: backport 2.x

#651 Add publish snapshots to maven via GHA
  .github/workflows/maven-publish.yml
  build.gradle
Labels: backport 2.x

#656 Add release notes for 2.6.0
  release-notes/opensearch-reporting.release-notes-2.6.0.0.md
Labels: backport 2.x, backport 2.6

#665 fix maven publish workflow
  .github/workflows/maven-publish.yml
Labels: backport 1.x, backport 2.x
