Repository opensearch-project/reporting, pull requests merged in 2023-01, with the labels that each got.

#611 [Backport 2.3] Use front-end report generation instead of chromium
  .github/workflows/dashboards-reports-test-and-build-workflow.yml
  README.md
  dashboards-reports/.gitignore
  dashboards-reports/.opensearch_dashboards-plugin-helpers.json
  dashboards-reports/package.json
  dashboards-reports/public/components/context_menu/context_menu.js
  dashboards-reports/public/components/context_menu/context_menu_ui.js
  dashboards-reports/public/components/main/loading_modal/loading_modal.tsx
  dashboards-reports/public/components/main/main_utils.tsx
  dashboards-reports/public/components/utils/settings_service.ts
  dashboards-reports/public/components/visual_report/assets/report_styles.ts
  dashboards-reports/public/components/visual_report/constants.ts
  dashboards-reports/public/components/visual_report/generate_report.ts
  dashboards-reports/public/plugin.ts
  dashboards-reports/rendering-engine/headless-chrome/README.md
  dashboards-reports/rendering-engine/headless-chrome/build_headless_chrome.sh
  dashboards-reports/scripts/patch-html2canvas.js
  dashboards-reports/server/plugin.ts
  dashboards-reports/server/routes/lib/createReport.ts
  dashboards-reports/server/routes/report.ts
  dashboards-reports/server/routes/utils/__tests__/visualReportHelper.test.ts
  dashboards-reports/server/routes/utils/constants.ts
  dashboards-reports/server/routes/utils/types.ts
  dashboards-reports/server/routes/utils/visual_report/footer_template.html
  dashboards-reports/server/routes/utils/visual_report/header_template.html
  dashboards-reports/server/routes/utils/visual_report/visualReportHelper.ts
  dashboards-reports/translations/pl.json
  dashboards-reports/yarn.lock
Labels: backport 2.0, backport 2.1, backport 2.2, backport 2.4

#610 [Backport 1.2] Use front-end report generation instead of chromium
  .github/workflows/dashboards-reports-test-and-build-workflow.yml
  README.md
  dashboards-reports/.gitignore
  dashboards-reports/.opensearch_dashboards-plugin-helpers.json
  dashboards-reports/package.json
  dashboards-reports/public/components/context_menu/context_menu.js
  dashboards-reports/public/components/context_menu/context_menu_ui.js
  dashboards-reports/public/components/main/loading_modal/loading_modal.tsx
  dashboards-reports/public/components/main/main_utils.tsx
  dashboards-reports/public/components/utils/settings_service.ts
  dashboards-reports/public/components/visual_report/assets/report_styles.ts
  dashboards-reports/public/components/visual_report/constants.ts
  dashboards-reports/public/components/visual_report/generate_report.ts
  dashboards-reports/public/plugin.ts
  dashboards-reports/rendering-engine/headless-chrome/README.md
  dashboards-reports/rendering-engine/headless-chrome/build_headless_chrome.sh
  dashboards-reports/scripts/patch-html2canvas.js
  dashboards-reports/server/plugin.ts
  dashboards-reports/server/routes/lib/createReport.ts
  dashboards-reports/server/routes/report.ts
  dashboards-reports/server/routes/utils/__tests__/visualReportHelper.test.ts
  dashboards-reports/server/routes/utils/constants.ts
  dashboards-reports/server/routes/utils/types.ts
  dashboards-reports/server/routes/utils/visual_report/footer_template.html
  dashboards-reports/server/routes/utils/visual_report/header_template.html
  dashboards-reports/server/routes/utils/visual_report/visualReportHelper.ts
  dashboards-reports/translations/pl.json
  dashboards-reports/yarn.lock
Labels: backport 1.x, backport 1.3, backport 1.1, backport 1.0

#622 Remove unnecessary scripts after repo split
  build.gradle
  scripts/build.sh
Labels: backport 2.5

#624 Include integration tests in windows and macOS workflow
  .github/workflows/reports-scheduler-test-and-build-workflow.yml
  build-tools/esplugin-coverage.gradle
Labels: backport 2.5

#628 Add release notes for 2.5.0.0
  release-notes/opensearch-reporting.release-notes-2.5.0.0.md
Labels: backport 2.5, backport main
