Repository opensearch-project/reporting, pull requests merged in 2023-05, with the labels that each got.

#700 Add release notes for 1.3.10.0
  release-notes/opensearch-dashboards-reports.release-notes-1.3.10.0.md
Labels: backport main

#705 Add release notes for 2.8
  release-notes/opensearch-reporting.release-notes-2.8.0.0.md
Labels: backport 2.x, backport 2.8

#709 Removing guava dependency to fix jarhell
  build.gradle
  release-notes/opensearch-reporting.release-notes-2.8.0.0.md
Labels: backport 2.x, backport main
