Repository opensearch-project/reporting, pull requests merged in 2023-04, with the labels that each got.

#684 Add release notes for 2.7.0
  release-notes/opensearch-reporting.release-notes-2.7.0.0.md
Labels: backport 2.x, backport 2.7

#692 Update json version to 20230227
  build.gradle
Labels: backport 2.7

#689 Update Gradle Wrapper to 7.6.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: infrastructure
