Repository opensearch-project/reporting, pull requests merged in 2024-04, with the labels that each got.

#986 [1.3] Upgrade JSON to 20231013 to fix CVE-2023-5072
  build.gradle
Labels: backport 1.x

#987 update bwc version to 2.14.0
  build.gradle
Labels: maintenance

#992 tenancy access control
  README.md
  src/main/kotlin/org/opensearch/reportsscheduler/security/UserAccessManager.kt
Labels: enhancement, backport 2.x

#994 Add 2.14.0 release notes
  release-notes/opensearch-reporting.release-notes-2.14.0.0.md
Labels: backport 2.x
