Repository opensearch-project/reporting, pull requests merged in 2025-02, with the labels that each got.

#1069 support for date time parameters
  src/main/kotlin/org/opensearch/reportsscheduler/action/ReportInstanceActions.kt
  src/main/kotlin/org/opensearch/reportsscheduler/model/ReportDefinition.kt
Labels: enhancement, backport 2.x

#1074 [2.19] bump logback to 1.5.16
  build.gradle
Labels: maintenance, backport 2.x, backport main

#1077 Update gradle version to 8.12.0 for JDK23 support
  gradle/wrapper/gradle-wrapper.properties
Labels: release, v3.0.0

#1078 add release notes for 2.19.1 release
  release-notes/opensearch-reporting.release-notes-2.19.1.0.md
Labels: backport 2.19
